# SPDX-License-Identifier: GPL-3.0-or-later
efi:
  mountPoint: /boot/efi
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: EFI
defaultPartitionTableType: gpt
requiredPartitionTableType:
- gpt
defaultFileSystemType: ext4
availableFileSystemTypes:
- ext4
initialPartitioningChoice: none
allowManualPartitioning: true
userSwapChoices:
- small
- none
initialSwapChoice: small
luksGeneration: luks1
lvm:
  enable: false
