# SPDX-License-Identifier: GPL-3.0-or-later
dontChroot: false
timeout: 180
script:
- /usr/share/abs/bootstrap/install.sh --user "${USER}" --apply
- /usr/share/abs/installer-finalize.sh
i18n:
  name: Deploy ABS Linux desktop
