# SPDX-License-Identifier: GPL-3.0-or-later
defaultGroups:
- sudo
- audio
- video
- plugdev
- netdev
sudoersGroup: sudo
setRootPassword: false
doAutologin: false
passwordRequirements:
  nonempty: true
  minLength: 8
