#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
import json
import subprocess
if json.loads(subprocess.check_output(['abs-capabilities'], text=True))['touchscreen']:
    subprocess.Popen(['onboard'])
