modules-search:
- local
instances:
- id: abs-deploy
  module: shellprocess
  config: shellprocess-abs.conf
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - luksbootkeyfile
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - hwclock
  - services-systemd
  - shellprocess@abs-deploy
  - grubcfg
  - bootloader
  - packages
  - initramfscfg
  - initramfs
  - umount
- show:
  - finished
branding: abs
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
